CROSS_COMPILE = arm-none-linux-gnueabi-
STRIP = $(CROSS_COMPILE)strip
CC = $(CROSS_COMPILE)gcc

OBJS+=$(filter %.o,$(SRC:.c=.o))

all: $(TARGET)

%.o: %.c
	@rm -f $@
	$(CROSS_COMPILE) $(CFLAGS) -c $< -o $@

version:
	bash gen_version.sh > version.h

$(TARGET): version $(OBJS)
	$(CROSS_COMPILE) $(OBJS) $(LDFLAGS) -o $@
	$(STRIP) $(TARGET)

clean:
	@for i in $(OBJS); do (if test -e "$$i"; then ( rm $$i ); fi ); done
	@rm -f $(TARGET)

